services:

  wordpress:
    image: wordpress:php8.4-apache
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wordpress:/var/www/html
      
  db:
    image: mariadb:lts-ubi9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
      MARIADB_DATABASE: "my_database"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
  
  backup:
    image: mariadb:lts-ubi9 # Gebruik dezelfde image om mariadb-dump te garanderen
    profiles: ["backup"] # Maakt de service standaard niet actief
    volumes:
      # BELANGRIJK: Mount de lokale host map (met backups) in de container
      - ./db_backup:/backups
    # De command definieert de dump-logica, volledig in de container
    command: >
      bash -c "mariadb-dump
      --host=db
      --all-databases
      -u root
      -p$$MARIADB_ROOT_PASSWORD
      | gzip > /backups/db_dump_$(date +%Y%m%d_%H%M%S).sql.gz"
    environment:
      # Haal het wachtwoord op dezelfde manier op als de db service
      MARIADB_ROOT_PASSWORD: "secret"
    depends_on:
      - db
  
  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secret
    depends_on:
      - db

volumes:
  wordpress:
  mariadb_data: